#!/bin/sh -eu

# Note: this script is only run once when the postgres volume is created. To
# run it again:
#
#     docker volume rm srht-postgres-data

password='$2b$12$mlcAuUeU5reidsdPcZm/kOR4EWkZE2lbMvyVSHLpDuzDtm6MGn0Ne'
client_secret='3eeeef2fd9d1e0176a50ee76d3382f7211231b832852bdfc3569a3bb5512158a19b1262b73ea735059004fd3ded53303e42f605e68ccbc9d3af84a373331aa9d'
token='dab72a400c2e5be8fe175b2a0eebba28ede9c84aa4be024f02a4095ccedc4dcd4c63d18768fc80b14f8b35c45586d5b15a3231ac6acf0b4ca0b2524fce353cb1'

createdb meta.sr.ht
psql -d meta.sr.ht </data/meta.sr.ht.sql
psql -d meta.sr.ht <<EOF
INSERT INTO "user" (id, created, updated, username, password, email, user_type)
VALUES (1, NOW(), NOW(), 'root', '$password', 'root@localhost', 'ADMIN');

INSERT INTO oauth2_grant(issued, expires, comment, token_hash, user_id, grants)
VALUES (NOW(), NOW() + interval '100 years', 'Automatically-generated by sr.ht-container-compose',
	'$token', 1, '');

INSERT INTO oauthclient (created, updated, user_id, client_name, client_id,
	client_secret_hash, client_secret_partial, redirect_uri, preauthorized)
VALUES
	(NOW(), NOW(), 1, 'todo.sr.ht', 'todo', '$client_secret', '3387e161',
		'http://127.0.0.1:5003/oauth/callback', TRUE),
	(NOW(), NOW(), 1, 'git.sr.ht', 'git', '$client_secret', '3387e161',
		'http://127.0.0.1:5001/oauth/callback', TRUE),
	(NOW(), NOW(), 1, 'man.sr.ht', 'man', '$client_secret', '3387e161',
		'http://127.0.0.1:5004/oauth/callback', TRUE),
	(NOW(), NOW(), 1, 'paste.sr.ht', 'paste', '$client_secret', '3387e161',
		'http://127.0.0.1:5011/oauth/callback', TRUE),
	(NOW(), NOW(), 1, 'hub.sr.ht', 'hub', '$client_secret', '3387e161',
		'http://127.0.0.1:5011/oauth/callback', TRUE),
	(NOW(), NOW(), 1, 'lists.sr.ht', 'lists', '$client_secret', '3387e161',
		'http://127.0.0.1:5011/oauth/callback', TRUE);
EOF

createdb todo.sr.ht
psql -d todo.sr.ht </data/todo.sr.ht.sql

createdb git.sr.ht
psql -d git.sr.ht </data/git.sr.ht.sql

createdb man.sr.ht
psql -d man.sr.ht </data/man.sr.ht.sql

createdb paste.sr.ht
psql -d paste.sr.ht </data/paste.sr.ht.sql

createdb hub.sr.ht
psql -d hub.sr.ht </data/hub.sr.ht.sql

createdb lists.sr.ht
psql -d lists.sr.ht </data/lists.sr.ht.sql
